version: "2.4"
services:
  minebot:
    environment:
      SERVER_HOST: mineserver
      SERVER_PORT: 25565
      VIEWER_PORT: 3000
    build:
      context: ./minebot
      dockerfile: Dockerfile.minebot
    depends_on:
      mineserver:
        condition: service_healthy
    ports:
      - "3000:3000"
  mineserver:
    build:
      context: ./mineserver
      dockerfile: Dockerfile.mineserver
    ports:
      - "25565:25565"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:25565"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 60s
